### ISSUE TITLE
api update 

### ISSUE THREAD

**Issue by duocaideyu** [Sneezry/Kepler#5]
OReilly api has changed ，the new api is learning.oreilly.com. but your project Kelper  in't update.

**Comment by himawariinthehouse** [comment]
can you fix it?

**Comment by lixinf** [comment]
Hi, Who can update the software? it doesn't work now

**Comment by polyrabbit** [comment]
Hi all, I just sent a PR (#6) addressing your issue. If you are in a emergency, please try my [fork](https://github.com/polyrabbit/Kepler).

**Comment by lixinf** [comment]
Thank you very much发送自我的三星盖乐世智能手机。
-------- 原始信息 --------发件人： Chang Xin Miao <notifications@github.com> 日期: 2019/2/19  14:32  (GMT+08:00) 收件人： Sneezry/Kepler <Kepler@noreply.github.com> 抄送： lixinf <lixinf@163.com>, Comment <comment@noreply.github.com> 主题： Re: [Sneezry/Kepler] api update  (#5) Hi all, I just sent a PR (#6) addressing your issue. If you are in a emergency, please try my fork.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Sneezry/Kepler","title":"Sneezry/Kepler","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Sneezry/Kepler"}},"updates":{"snippets":[{"icon":"PERSON","message":"@polyrabbit in #5: Hi all, I just sent a PR (#6) addressing your issue. If you are in a emergency, please try my [fork](https://github.com/polyrabbit/Kepler)."}],"action":{"name":"View Issue","url":"https://github.com/Sneezry/Kepler/issues/5#issuecomment-465003089"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Sneezry/Kepler/issues/5#issuecomment-465003089",
"url": "https://github.com/Sneezry/Kepler/issues/5#issuecomment-465003089",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ityuhui** [comment]
Thank you @polyrabbit .

The fix is OK. It help me a lot.
